############################################################################
# apps/examples/poll_test/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_POLL_TEST_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_POLL_TEST_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_POLL_TEST_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_POLL_TEST)

MAINSRC = poll_test_main.c

include $(APPDIR)/Application.mk
